### ISSUE TITLE
Can't see my pet

### ISSUE THREAD

**Issue by CrazyNutLz** [SmallCodee/SmallPets#3]
When I summon my pet, the server will report a warn
And I can't see my pet either

This is the report 
Server is Akarin-1.16.1

`[14:24:27 INFO]: CrazyNut issued server command: /smallpets`
`[14:24:30 WARN]: [SmallPets] Plugin SmallPets vbeta-4.2 generated an exception while executing task 4254
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
        at it.smallcode.smallpets.v1_16.pets.Monkey.spawnArmorstandWithPackets(Monkey.java:79) ~[?:?]
        at it.smallcode.smallpets.v1_15.SamplePet$3.run(SamplePet.java:154) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Akarin-"3cd947f"]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Akarin-"3cd947f"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Akarin-"3cd947f"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by hannest03** [comment]
You need to use the latest protocollib devbuild.

**Comment by CrazyNutLz** [comment]
> You need to use the latest protocollib devbuild.

Thanks a lot

**Comment by hannest03** [comment]
No problem
